schemaVersion: 2.0.0

metadataTest:
  # Image has expected default metadata
  env:
    - key: GOPATH
      value: /go
  exposedPorts: []
  volumes: []
  entrypoint: []

fileExistenceTests:
  # Main binary exists
  - name: Check existance of mytestfile.txt
    path: /gaurav/pandey/mytestfile.txt
    shouldExist: true
    permissions: "-rw-r--r--"

commandTests:
  # Main binary can print its version
  - name: go version
    command: go
    args: ["version"]
    expectedOutput: ["go version go1.14.6"]
    exitCode: 0
  # Can compile a valid "hello world"
  - name: hello world
    setup: [["wget", "https://raw.githubusercontent.com/go-training/helloworld/master/main.go"]]
    command: go
    args: ["run", "main.go"]
    expectedOutput: ["Helloo World!!"]
    exitCode: 0
    teardown: [["rm", "main.go"]]
